parent=keycloak
import=common/keycloak
styles=css/login.css

# Pega las URL HTTPS de tus documentos de Google en modo lectura.
# Si una URL queda vacia, su enlace no se muestra.
loginHelpUrl=https://docs.google.com/document/d/1KHoPl41aEkJlEZxL7HQySgPG0622XX_xySlm4PLSVNc/edit?usp=sharing
freeOtpHelpUrl=https://docs.google.com/document/d/1KHoPl41aEkJlEZxL7HQySgPG0622XX_xySlm4PLSVNc/edit?tab=t.0#heading=h.rgxfm1dq0m7z
# Opcional: enlace directo a la seccion de uso diario del manual FreeOTP.
# Si queda vacio, se utiliza freeOtpHelpUrl.
freeOtpUsageHelpUrl=https://docs.google.com/document/d/1KHoPl41aEkJlEZxL7HQySgPG0622XX_xySlm4PLSVNc/edit?tab=t.0#heading=h.lkuytvyl64il

# Enlace directo a la seccion de ingreso manual de la clave FreeOTP.
# Se muestra dentro de "No consigues escanear" solo si tiene una URL HTTPS.
freeOtpManualHelpUrl=https://docs.google.com/document/d/1KHoPl41aEkJlEZxL7HQySgPG0622XX_xySlm4PLSVNc/edit?tab=t.0#heading=h.gqypbn4fjxte
